### ISSUE TITLE
Word change recommendation

### ISSUE THREAD

**Issue by Patriciasparreo** [ChandlerKilpatrick1/CS-A3#2]
Hi Chandler,
I'd suggest that you revise this sentence...

This **repo** is designed to showcase the work that I, Chandler Kilpatrick, have done. 

...and replace it with this one:

This **repository** is designed to showcase the work that I, Chandler Kilpatrick, have done.

**Comment by ChandlerKilpatrick1** [comment]
Thanks very much!
